name: deploy

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/sendmailer:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/sendmailer:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd ${{ secrets.VPS_DIR }}
            git pull
            docker stop ${{ secrets.TAG_CONTAINER}}
            docker rm ${{ secrets.TAG_CONTAINER}}            
            docker pull ${{ secrets.DOCKERHUB_USERNAME}}/sendmailer:latest
            docker run -d --name ${{ secrets.TAG_CONTAINER}} --env-file .env ${{ secrets.DOCKERHUB_USERNAME}}/sendmailer:latest
            docker image prune -a -f
